### ISSUE TITLE
Using graphics tablet with pen as input

### ISSUE THREAD

**Issue by michaelsjackson** [vizicist/palette#1]
Dear Tim, read your post in the keykit mailing list about the new long term project.

My first idea would be allowing normal, cheap, simple graphics tablets with a pen as an input system.  Great would be if even keykit would support this, to output some midi or osc data. Or in your new system, any kind of data which can be useful musically.

Best greetings.  Thanks for all your great tools so far!  You and Phil Tipping (developed Sequetron) are my absolute all time midi master heros!  Thanks my friends.

**Comment by vizicist** [comment]
Although the current Palette code now has Sensel Morph support built-in for ease of distribution, I have usually separated out cursor device input into a separate process and used TUIO (a format for cursor events over OSC) as the protocol.   This has been a big win - it made coverting from use of the Microsft Kinect to the Sensel Morph incredibly easy.  A very important feature for me is to have 3D input from the cursors, and some graphics tablets can produce that either using pen pressure and/or the angle of the pen.  One big reason I use TUIO as the protocol is that they designed in support for 3D cursors.

Writing a TUIO output driver for a new input device is usually quite straightforward, as long as the device has an API that gives access to the data - that's the biggest hurdle sometimes.  KeyKit has had TUIO/OSC support for a long time in the user-defined library.  I originally started using TUIO/OSC for input in KeyKit back in the early 2000's when I was using the Fingerworks iGesture pads (RIP).   OSC and MIDI output are available as well - I use OSC for communicating with visual systems (Resolume) and VST hosts (Ploge Bidule).

So, all good, thanks for the input!

**Comment by gedw99** [comment]
what about using GIOUI to make any mobile or tablet into the same thing ?

is the Sensel Morph more sensitive than a tablet in some way ?

**Comment by vizicist** [comment]
> what about using GIOUI to make any mobile or tablet into the same thing ?

I'm very slowly moving toward replacing the Python GUI with Go, using a small subset of ebiten to draw things.  That work is actually focused more on reimplementing the KeyKit window system than on replacing the Python GUI, but I do want to replace the Python GUI eventually.  The final Palette visuals rely heavily on Resolume and FreeFrame plugins, which aren't supported on mobile/tablet, so that's not possible without creating a completely different system.

> is the Sensel Morph more sensitive than a tablet in some way ?

Yes, it's multitouch and pressure-sensitive, with an extreme dynamic range (light to hard pressure).  To give you an idea of how sensitive, you can literally blow on it and it will sense it.  This makes it possible to caress the pads in a finger painting like experience that is natural and expressive.  The new Erae Touch product (see embodme.com) is similar in sensitivity and larger, but five times as expensive.

**Comment by vizicist** [comment]
That said, the engine has an API for accepting cursor events (I've now moved away from TUIO), so that opens the door to interacting using other devices, as well as doing programmatic/generative things.

**Comment by gedw99** [comment]
I think a gioui gui will work well with that api . I saw your using nats and nats is quite easy to get to work with gui .

for web you can use their web socket e posed via nats server works. That’s because gioui compiles to wasm.

For desktop and mobile the nats.go client works using its tcp transport. 

As far as sound beep works but so does the sound lib from ebiten.

**Comment by michaelsjackson** [comment]
Played a bit using any set of tools available to linux users, here something for the interested.

 # generating midi events from graphics tablet data
 # tested with XP-PEN Deco 03.
 # What I have so far

`#!/usr/bin/env bash
xev | grep --line-buffered -E -o '[[:digit:]]+,[[:digit:]]+' | while read line;do myarray=($(echo $line | tr "," "\n"));echo x ${myarray[0]}  y ${myarray[1]};sendmidi dev 'Midi Through Port-3' cc $1 $((${myarray[0]}%127));sendmidi dev 'Midi Through Port-3' cc $2 $((${myarray[1]}%127));done
`

As xev produces each time two lines of output (one for global screen size, another for local xev window size), I need to find a way splitting per line, then generating 4 events, would be cooler. Any suggestions from command line experts are welcome.
